-- ============================================================
-- BRAHMI SCRIPT LEARNING APP - COMPLETE SUPABASE SCHEMA (5 TABLES)
-- ============================================================

-- 1. PROFILES TABLE
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  full_name text,
  avatar_url text,
  provider text,
  preferred_language text default 'hi',
  daily_goal_minutes integer default 10,
  last_sign_in_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create policy "Users can view own profile" on public.profiles for select to authenticated using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);
create policy "Users can insert own profile" on public.profiles for insert to authenticated with check (auth.uid() = id);

-- Auto create/update profile on auth.users insert
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url, provider, last_sign_in_at)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name'),
    coalesce(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture'),
    new.raw_app_meta_data->>'provider',
    new.last_sign_in_at
  )
  on conflict (id) do update set
    email = excluded.email,
    full_name = excluded.full_name,
    avatar_url = excluded.avatar_url,
    provider = excluded.provider,
    last_sign_in_at = excluded.last_sign_in_at,
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();


-- 2. LESSON PROGRESS TABLE
create table if not exists public.lesson_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  module_id text not null,
  lesson_id text not null,
  status text not null default 'not_started' check (status in ('not_started', 'in_progress', 'completed')),
  progress_percentage integer not null default 0 check (progress_percentage >= 0 and progress_percentage <= 100),
  last_accessed timestamptz not null default now(),
  completed_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint lesson_progress_user_module_lesson_key unique (user_id, module_id, lesson_id)
);

create index if not exists lesson_progress_user_module_idx on public.lesson_progress (user_id, module_id);
create index if not exists lesson_progress_module_lesson_idx on public.lesson_progress (module_id, lesson_id);

alter table public.lesson_progress enable row level security;

create policy "Users can view own lesson progress" on public.lesson_progress for select to authenticated using (auth.uid() = user_id);
create policy "Users can insert own lesson progress" on public.lesson_progress for insert to authenticated with check (auth.uid() = user_id);
create policy "Users can update own lesson progress" on public.lesson_progress for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);


-- 3. USER STREAKS TABLE
create table if not exists public.user_streaks (
  user_id uuid primary key references auth.users (id) on delete cascade,
  current_streak integer not null default 0,
  longest_streak integer not null default 0,
  last_login_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_streaks enable row level security;

create policy "Users can view own streaks" on public.user_streaks for select to authenticated using (auth.uid() = user_id);
create policy "Users can update own streaks" on public.user_streaks for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can insert own streaks" on public.user_streaks for insert to authenticated with check (auth.uid() = user_id);


-- 4. USER BADGES TABLE
create table if not exists public.user_badges (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  badge_id text not null,
  badge_name text not null,
  module_id text,
  unlocked_at timestamptz not null default now(),
  constraint user_badges_user_badge_key unique (user_id, badge_id)
);

alter table public.user_badges enable row level security;

create policy "Users can view own badges" on public.user_badges for select to authenticated using (auth.uid() = user_id);
create policy "Users can insert own badges" on public.user_badges for insert to authenticated with check (auth.uid() = user_id);


-- 5. USER SETTINGS TABLE
create table if not exists public.user_settings (
  user_id uuid primary key references auth.users (id) on delete cascade,
  sound_effects_enabled boolean not null default true,
  voice_audio_enabled boolean not null default true,
  haptic_feedback_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_settings enable row level security;

create policy "Users can view own settings" on public.user_settings for select to authenticated using (auth.uid() = user_id);
create policy "Users can update own settings" on public.user_settings for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users can insert own settings" on public.user_settings for insert to authenticated with check (auth.uid() = user_id);
