'use client'

/**
 * QuizEngine — Dynamic quiz runner
 *
 * Accepts a list of QuizQuestions generated by the course engine
 * and renders them one at a time, collecting answers, tracking score,
 * and firing onComplete with results.
 */

import { useState, useCallback } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import type { QuizQuestion, QuizOption } from '@/types/course'

interface QuizEngineProps {
  questions: QuizQuestion[]
  moduleId: string
  onComplete: (result: QuizResult) => void
  onExit?: () => void
  title?: string
}

export interface QuizResult {
  totalQuestions: number
  correctAnswers: number
  score: number // percentage
  answers: Array<{ questionId: string; selected: string; correct: boolean }>
}

// ── Option button ──────────────────────────────────────────────

interface OptionButtonProps {
  option: QuizOption
  selected: string | null
  showAnswer: boolean
  onClick: () => void
}

function OptionButton({ option, selected, showAnswer, onClick }: OptionButtonProps) {
  const isSelected = selected === option.text
  const isCorrect = option.isCorrect
  const reveal = showAnswer && isSelected

  let stateClass = 'bg-[#2a2420] border-[#D4AF37]/20 text-[#E6D8B8] hover:border-[#D4AF37]/60 hover:bg-[#2a2420]'
  if (reveal && isCorrect) stateClass = 'bg-green-600/20 border-green-500 text-green-400'
  else if (reveal && !isCorrect) stateClass = 'bg-red-600/20 border-red-500 text-red-400'
  else if (showAnswer && isCorrect) stateClass = 'bg-green-600/20 border-green-500/50 text-green-400/70'

  return (
    <motion.button
      whileHover={!showAnswer ? { scale: 1.02 } : undefined}
      whileTap={!showAnswer ? { scale: 0.98 } : undefined}
      onClick={!showAnswer ? onClick : undefined}
      disabled={showAnswer}
      className={`
        w-full flex items-center justify-between px-5 py-4 rounded-2xl border-2
        font-medium text-base transition-all text-left cursor-pointer disabled:cursor-default
        ${stateClass}
      `}
    >
      <div className="flex items-center gap-3">
        {/* Brahmi character preview if available */}
        {option.brahmi && (
          <span className="text-2xl text-[#D4AF37] font-brahmi shrink-0">{option.brahmi}</span>
        )}
        <span>{option.text}</span>
      </div>

      {showAnswer && (
        <span className="shrink-0 text-lg">
          {isCorrect ? '✅' : isSelected ? '❌' : ''}
        </span>
      )}
    </motion.button>
  )
}

// ── Score result screen ─────────────────────────────────────────

function ScoreScreen({
  result,
  onComplete,
  onRetry,
}: {
  result: QuizResult
  onComplete: () => void
  onRetry: () => void
}) {
  const isPerfect = result.score === 100
  const isGood = result.score >= 70

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
      className="flex flex-col items-center gap-6 px-6 py-12 text-center max-w-md mx-auto"
    >
      <motion.div
        initial={{ scale: 0 }}
        animate={{ scale: 1 }}
        transition={{ type: 'spring', stiffness: 300, delay: 0.2 }}
        className="text-7xl"
      >
        {isPerfect ? '🏆' : isGood ? '⭐' : '📚'}
      </motion.div>

      <div>
        <h2 className="text-3xl font-bold text-[#D4AF37] font-serif">
          {isPerfect ? 'शानदार!' : isGood ? 'बहुत अच्छा!' : 'और अभ्यास करें!'}
        </h2>
        <p className="text-[#E6D8B8]/60 mt-2 text-sm">
          {result.correctAnswers} / {result.totalQuestions} सही
        </p>
      </div>

      {/* Score ring */}
      <div className="relative w-28 h-28">
        <svg className="w-full h-full -rotate-90" viewBox="0 0 100 100">
          <circle cx="50" cy="50" r="42" fill="none" stroke="#2a2420" strokeWidth="10" />
          <motion.circle
            cx="50" cy="50" r="42"
            fill="none"
            stroke={isPerfect ? '#D4AF37' : isGood ? '#E69A47' : '#E6D8B8'}
            strokeWidth="10"
            strokeLinecap="round"
            strokeDasharray={`${2 * Math.PI * 42}`}
            strokeDashoffset={`${2 * Math.PI * 42 * (1 - result.score / 100)}`}
            initial={{ strokeDashoffset: `${2 * Math.PI * 42}` }}
            animate={{ strokeDashoffset: `${2 * Math.PI * 42 * (1 - result.score / 100)}` }}
            transition={{ duration: 1.2, ease: 'easeOut', delay: 0.4 }}
          />
        </svg>
        <div className="absolute inset-0 flex items-center justify-center">
          <span className="text-2xl font-bold text-[#D4AF37]">{result.score}%</span>
        </div>
      </div>

      <div className="flex flex-col gap-3 w-full">
        <motion.button
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
          onClick={onComplete}
          className="w-full px-6 py-4 rounded-2xl bg-[#D4AF37] text-[#1a1613] font-bold text-lg hover:brightness-110 transition-all shadow-lg"
        >
          आगे बढ़ें →
        </motion.button>
        {!isPerfect && (
          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={onRetry}
            className="w-full px-6 py-3 rounded-2xl bg-[#2a2420] border border-[#D4AF37]/30 text-[#D4AF37] font-medium hover:border-[#D4AF37] transition-all"
          >
            फिर से करें
          </motion.button>
        )}
      </div>
    </motion.div>
  )
}

// ── Main quiz engine ────────────────────────────────────────────

export default function QuizEngine({ questions, onComplete, onExit, title }: QuizEngineProps) {
  const [currentIndex, setCurrentIndex] = useState(0)
  const [selected, setSelected] = useState<string | null>(null)
  const [showAnswer, setShowAnswer] = useState(false)
  const [answers, setAnswers] = useState<QuizResult['answers']>([])
  const [done, setDone] = useState(false)

  const current = questions[currentIndex]
  const isLast = currentIndex === questions.length - 1
  const progressPercent = Math.round(((currentIndex + 1) / questions.length) * 100)

  const handleSelect = useCallback((option: QuizOption) => {
    if (showAnswer) return
    setSelected(option.text)
    setShowAnswer(true)
    setAnswers(prev => [
      ...prev,
      { questionId: current.id, selected: option.text, correct: option.isCorrect },
    ])
  }, [showAnswer, current?.id])

  const handleNext = useCallback(() => {
    if (isLast) {
      setDone(true)
    } else {
      setCurrentIndex(i => i + 1)
      setSelected(null)
      setShowAnswer(false)
    }
  }, [isLast])

  const handleRetry = useCallback(() => {
    setCurrentIndex(0)
    setSelected(null)
    setShowAnswer(false)
    setAnswers([])
    setDone(false)
  }, [])

  // Build result when done
  const correctCount = answers.filter(a => a.correct).length
  const result: QuizResult = {
    totalQuestions: questions.length,
    correctAnswers: correctCount,
    score: questions.length > 0 ? Math.round((correctCount / questions.length) * 100) : 0,
    answers,
  }

  if (!questions || questions.length === 0) {
    return (
      <div className="flex items-center justify-center min-h-[60vh] text-[#E6D8B8]/40">
        कोई प्रश्न नहीं मिले।
      </div>
    )
  }

  if (done) {
    return (
      <ScoreScreen
        result={result}
        onComplete={() => onComplete(result)}
        onRetry={handleRetry}
      />
    )
  }

  return (
    <div className="flex flex-col min-h-screen bg-[#1C1C1C] text-[#E6D8B8]">

      {/* ── Header ─────────────────────────────────────────── */}
      <div className="sticky top-0 z-40 bg-[#1C1C1C]/90 backdrop-blur-sm border-b border-[#D4AF37]/10">
        <div className="flex items-center gap-3 px-4 py-3">
          {onExit && (
            <button onClick={onExit} className="shrink-0 text-[#D4AF37] p-1.5 rounded-full hover:bg-[#2a2420] transition-all">
              ✕
            </button>
          )}
          <div className="flex-1 h-2 bg-[#2a2420] rounded-full overflow-hidden">
            <motion.div
              className="h-full bg-gradient-to-r from-[#D4AF37] to-[#E69A47] rounded-full"
              animate={{ width: `${progressPercent}%` }}
              transition={{ duration: 0.3 }}
            />
          </div>
          <span className="shrink-0 text-xs text-[#D4AF37]/60 tabular-nums font-medium">
            {currentIndex + 1}/{questions.length}
          </span>
        </div>
        {title && (
          <div className="px-4 pb-2 text-[10px] uppercase tracking-widest text-[#E69A47]/60 font-bold">
            {title}
          </div>
        )}
      </div>

      {/* ── Question area ──────────────────────────────────── */}
      <div className="flex-1 flex flex-col justify-center px-4 py-8 max-w-lg mx-auto w-full">
        <AnimatePresence mode="wait">
          <motion.div
            key={currentIndex}
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -30 }}
            transition={{ duration: 0.25 }}
            className="flex flex-col gap-6"
          >
            {/* Question */}
            <div className="text-center">
              <p className="text-lg md:text-xl font-medium text-[#E6D8B8]/90 leading-relaxed">
                {current.question}
              </p>
            </div>

            {/* Options */}
            <div className="flex flex-col gap-3">
              {current.options?.map(option => (
                <OptionButton
                  key={option.id}
                  option={option}
                  selected={selected}
                  showAnswer={showAnswer}
                  onClick={() => handleSelect(option)}
                />
              ))}
            </div>

            {/* Next button (appears after answering) */}
            <AnimatePresence>
              {showAnswer && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0 }}
                >
                  <button
                    onClick={handleNext}
                    className="w-full py-4 rounded-2xl bg-[#D4AF37] text-[#1a1613] font-bold text-lg hover:brightness-110 transition-all shadow-lg mt-2"
                  >
                    {isLast ? 'परिणाम देखें →' : 'अगला →'}
                  </button>
                </motion.div>
              )}
            </AnimatePresence>
          </motion.div>
        </AnimatePresence>
      </div>
    </div>
  )
}
